services:
  app: # Define a service named 'app' for your Go application
    build:
      context: . # Look for the Dockerfile in the current directory
      dockerfile: Dockerfile # Specify the name of your Dockerfile
    ports:
      - "3443:3443" # Map host port
    volumes:
      - ./collections:/root/collections
    restart: always # Always restart the container if it stops
